buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
    }
}

allprojects {
    repositories {
        maven {
            url "https://maven.aliyun.com/repository/central"
            content {
                includeGroup "com.microsoft.onnxruntime"
                includeGroup "com.google.crypto.tink"
            }
        }
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
