package com.ywwynm.everythingdone.model

import android.annotation.SuppressLint
import android.content.Context
import android.content.SharedPreferences
import com.ywwynm.everythingdone.Def
import com.ywwynm.everythingdone.database.ThingDAO
import com.ywwynm.everythingdone.utils.LocaleUtil

/**
 * Created by ywwynm on 2015/7/11.
 * Model layer for database generated by table things_count
 */
@SuppressLint("CommitPrefEdits")
open class ThingsCounts private constructor(context: Context?) {

    private var mCounts: SharedPreferences? = null

    init {
        mCounts = context!!.getSharedPreferences(
                Def.Meta.THINGS_COUNTS_NAME, Context.MODE_PRIVATE)
        if (mCounts!!.getInt("0_0", -1) == -1) {
            init()
        } else {
            checkSelf(context)
        }
    }

    private fun checkSelf(context: Context?) {
        val dao = ThingDAO.getInstance(context)
        var type = Thing.NOTE
        while (type <= Thing.NOTIFY_EMPTY_DELETED) {
            var totalCount = 0
            var state = Thing.UNDERWAY
            while (state <= Thing.DELETED) {
                val cursor = dao!!.getThingsCursor("type=" + type + " and state=" + state)
                val cursorCount = cursor!!.getCount()
                val prefCount = getCount(type, state)
                if (cursorCount != prefCount) {
                    setCounts(type, state, cursorCount)
                }
                totalCount += cursorCount
                cursor.close()
                state++
            }
            if (getCount(type, ALL) < totalCount) {
                setCounts(type, ALL, totalCount)
            }
            type++
        }
    }

    open fun getCount(type: Int, state: Int): Int {
        return mCounts!!.getInt(type.toString() + "_" + state, 0)
    }

    open fun getThingsCountForActivityHeader(limit: Int): Int {
        var count = 0
        when (limit) {
            Def.LimitForGettingThings.ALL_UNDERWAY -> {
                var i = Thing.NOTE
                while (i <= Thing.WELCOME_UNDERWAY) {
                    count += getCount(i, Thing.UNDERWAY)
                    i++
                }
                count += getCount(Thing.NOTIFICATION_UNDERWAY, Thing.UNDERWAY)
            }
            Def.LimitForGettingThings.NOTE_UNDERWAY -> {
                count = getCount(Thing.NOTE, Thing.UNDERWAY) +
                        getCount(Thing.WELCOME_NOTE, Thing.UNDERWAY) +
                        getCount(Thing.NOTIFICATION_NOTE, Thing.UNDERWAY)
            }
            Def.LimitForGettingThings.REMINDER_UNDERWAY -> {
                count = getCount(Thing.REMINDER, Thing.UNDERWAY) +
                        getCount(Thing.WELCOME_REMINDER, Thing.UNDERWAY) +
                        getCount(Thing.NOTIFICATION_REMINDER, Thing.UNDERWAY)
            }
            Def.LimitForGettingThings.HABIT_UNDERWAY -> {
                count = getCount(Thing.HABIT, Thing.UNDERWAY) +
                        getCount(Thing.WELCOME_HABIT, Thing.UNDERWAY) +
                        getCount(Thing.NOTIFICATION_HABIT, Thing.UNDERWAY)
            }
            Def.LimitForGettingThings.GOAL_UNDERWAY -> {
                count = getCount(Thing.GOAL, Thing.UNDERWAY) +
                        getCount(Thing.WELCOME_GOAL, Thing.UNDERWAY) +
                        getCount(Thing.NOTIFICATION_GOAL, Thing.UNDERWAY)
            }
            Def.LimitForGettingThings.ALL_FINISHED -> {
                var i = Thing.NOTE
                while (i <= Thing.NOTIFICATION_GOAL) {
                    count += getCount(i, Thing.FINISHED)
                    i++
                }
            }
            Def.LimitForGettingThings.ALL_DELETED -> {
                var i = Thing.NOTE
                while (i <= Thing.NOTIFICATION_GOAL) {
                    count += getCount(i, Thing.DELETED)
                    i++
                }
            }
        }
        return count
    }

    open fun getCompletionRate(limit: Int): String? {
        val counts = IntArray(2)
        when (limit) {
            Def.LimitForGettingThings.ALL_UNDERWAY,
            Def.LimitForGettingThings.ALL_FINISHED,
            Def.LimitForGettingThings.ALL_DELETED -> {
                var i = Thing.NOTE
                while (i <= Thing.GOAL) {
                    counts[0] += getCount(i, Thing.FINISHED)
                    counts[1] += getCount(i, ALL)
                    i++
                }
            }
            Def.LimitForGettingThings.NOTE_UNDERWAY -> {
                counts[0] = getCount(Thing.NOTE, Thing.FINISHED)
                counts[1] = getCount(Thing.NOTE, ALL)
            }
            Def.LimitForGettingThings.REMINDER_UNDERWAY -> {
                counts[0] = getCount(Thing.REMINDER, Thing.FINISHED)
                counts[1] = getCount(Thing.REMINDER, ALL)
            }
            Def.LimitForGettingThings.HABIT_UNDERWAY -> {
                counts[0] = getCount(Thing.HABIT, Thing.FINISHED)
                counts[1] = getCount(Thing.HABIT, ALL)
            }
            Def.LimitForGettingThings.GOAL_UNDERWAY -> {
                counts[0] = getCount(Thing.GOAL, Thing.FINISHED)
                counts[1] = getCount(Thing.GOAL, ALL)
            }
            else -> {}
        }
        return LocaleUtil.getPercentStr(counts[0], counts[1])
    }

    open fun handleCreation(type: Int) {
        updateCounts(type, Thing.UNDERWAY, 1)
        updateCounts(type, ALL, 1)
    }

    open fun handleUpdate(
            typeBefore: Int, stateBefore: Int,
            typeAfter: Int, stateAfter: Int, count: Int) {
        if (stateBefore != Thing.DELETED_FOREVER) {
            updateCounts(typeBefore, stateBefore, -count)
        }
        if (stateAfter != Thing.DELETED_FOREVER) {
            updateCounts(typeAfter, stateAfter, count)
            updateCounts(typeBefore, ALL, -count)
            updateCounts(typeAfter, ALL, count)
        }
    }

    private fun updateCounts(type: Int, state: Int, vary: Int) {
        var count = getCount(type, state)
        count += vary
        setCounts(type, state, count)
    }

    private fun setCounts(type: Int, state: Int, count: Int) {
        mCounts!!.edit().putInt(type.toString() + "_" + state, count).commit()
    }

    private fun init() {
        val editor = mCounts!!.edit()
        var i = Thing.NOTE
        while (i <= Thing.NOTIFY_EMPTY_DELETED) {
            var j = Thing.UNDERWAY
            while (j <= ALL) {
                editor.putInt(i.toString() + "_" + j, 0)
                j++
            }
            i++
        }

        var k = Thing.WELCOME_UNDERWAY
        while (k <= Thing.WELCOME_GOAL) {
            editor.putInt(k.toString() + "_" + Thing.UNDERWAY, 1)
            editor.putInt(k.toString() + "_" + ALL, 1)
            k++
        }

        editor.putInt(Thing.NOTIFY_EMPTY_FINISHED.toString() + "_" + Thing.UNDERWAY, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_FINISHED.toString() + "_" + ALL, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_DELETED.toString() + "_" + Thing.UNDERWAY, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_DELETED.toString() + "_" + ALL, 1)

        editor.commit()
    }

    companion object {
        const val TAG: String = "ThingsCounts"

        const val ALL: Int = Thing.DELETED + 1

        @JvmField
        var sThingsCounts: ThingsCounts? = null

        @JvmStatic
        fun getInstance(context: Context?): ThingsCounts? {
            if (sThingsCounts == null) {
                synchronized(ThingsCounts::class.java) {
                    if (sThingsCounts == null) {
                        sThingsCounts = ThingsCounts(context!!.getApplicationContext())
                    }
                }
            }
            return sThingsCounts
        }
    }
}
