package com.ywwynm.everythingdone.model

import android.annotation.SuppressLint
import android.content.Context
import android.content.SharedPreferences
import com.ywwynm.everythingdone.Def
import com.ywwynm.everythingdone.database.ThingDAO
import com.ywwynm.everythingdone.utils.LocaleUtil

/**
 * Created by ywwynm on 2015/7/11.
 * Translated to Kotlin by ywwynm and Claude Opus 4.7 on 2026/5/20.
 * Model layer for database generated by table things_count
 */
@SuppressLint("CommitPrefEdits")
open class ThingsCounts private constructor(context: Context?) {

    private var mCounts: SharedPreferences? = null

    init {
        mCounts = context!!.getSharedPreferences(
                Def.Meta.THINGS_COUNTS_NAME, Context.MODE_PRIVATE)
        if (mCounts!!.getInt("0_0", -1) == -1) {
            init()
        } else {
            checkSelf(context)
        }
    }

    private fun checkSelf(context: Context?) {
        val dao = ThingDAO.getInstance(context)
        var type = Thing.NOTE
        while (type <= Thing.NOTIFY_EMPTY_DELETED) {
            var totalCount = 0
            var state = Thing.UNDERWAY
            while (state <= Thing.DELETED) {
                val cursor = dao!!.getThingsCursor("type=$type and state=$state")
                val cursorCount = cursor!!.count
                val prefCount = getCount(type, state)
                if (cursorCount != prefCount) {
                    setCounts(type, state, cursorCount)
                }
                totalCount += cursorCount
                cursor.close()
                state++
            }
            if (getCount(type, ALL) < totalCount) {
                setCounts(type, ALL, totalCount)
            }
            type++
        }
    }

    open fun getCount(type: Int, state: Int): Int {
        return mCounts!!.getInt(type.toString() + "_" + state, 0)
    }

    open fun getThingsCountForStatus(status: Int, typeFilterMask: Int): Int {
        val mask = ThingWidgetInfo.normalizedTypeFilterMask(typeFilterMask)
        val state = when (status) {
            Def.ThingStatus.FINISHED -> Thing.FINISHED
            Def.ThingStatus.DELETED -> Thing.DELETED
            else -> Thing.UNDERWAY
        }
        var count = 0
        if (mask == ThingWidgetInfo.TYPE_FILTER_ALL) {
            var i = Thing.NOTE
            while (i <= Thing.WELCOME_UNDERWAY) {
                count += getCount(i, state)
                i++
            }
            if (state == Thing.UNDERWAY) {
                count += getCount(Thing.NOTIFICATION_UNDERWAY, Thing.UNDERWAY)
            }
        } else {
            val types = mutableListOf<Int>()
            if (mask and ThingWidgetInfo.TYPE_FILTER_NOTE != 0) types.add(Thing.NOTE)
            if (mask and ThingWidgetInfo.TYPE_FILTER_REMINDER != 0) types.add(Thing.REMINDER)
            if (mask and ThingWidgetInfo.TYPE_FILTER_HABIT != 0) types.add(Thing.HABIT)
            if (mask and ThingWidgetInfo.TYPE_FILTER_GOAL != 0) types.add(Thing.GOAL)
            for (type in types) {
                count += getCount(type, state)
                if (state == Thing.UNDERWAY) {
                    count += getCount(welcomeTypeForThingType(type), Thing.UNDERWAY)
                    count += getCount(notificationTypeForThingType(type), Thing.UNDERWAY)
                }
            }
        }
        return count
    }

    private fun welcomeTypeForThingType(type: Int): Int {
        return when (type) {
            Thing.REMINDER -> Thing.WELCOME_REMINDER
            Thing.HABIT -> Thing.WELCOME_HABIT
            Thing.GOAL -> Thing.WELCOME_GOAL
            else -> Thing.WELCOME_NOTE
        }
    }

    private fun notificationTypeForThingType(type: Int): Int {
        return when (type) {
            Thing.REMINDER -> Thing.NOTIFICATION_REMINDER
            Thing.HABIT -> Thing.NOTIFICATION_HABIT
            Thing.GOAL -> Thing.NOTIFICATION_GOAL
            else -> Thing.NOTIFICATION_NOTE
        }
    }

    open fun getCompletionRate(status: Int, typeFilterMask: Int): String? {
        val mask = ThingWidgetInfo.normalizedTypeFilterMask(typeFilterMask)
        val counts = IntArray(2)
        val types = when {
            mask == ThingWidgetInfo.TYPE_FILTER_ALL ->
                intArrayOf(Thing.NOTE, Thing.REMINDER, Thing.HABIT, Thing.GOAL)
            else -> {
                val list = mutableListOf<Int>()
                if (mask and ThingWidgetInfo.TYPE_FILTER_NOTE != 0) list.add(Thing.NOTE)
                if (mask and ThingWidgetInfo.TYPE_FILTER_REMINDER != 0) list.add(Thing.REMINDER)
                if (mask and ThingWidgetInfo.TYPE_FILTER_HABIT != 0) list.add(Thing.HABIT)
                if (mask and ThingWidgetInfo.TYPE_FILTER_GOAL != 0) list.add(Thing.GOAL)
                list.toIntArray()
            }
        }
        for (type in types) {
            counts[0] += getCount(type, Thing.FINISHED)
            counts[1] += getCount(type, ALL)
        }
        return LocaleUtil.getPercentStr(counts[0], counts[1])
    }

    open fun handleCreation(type: Int) {
        updateCounts(type, Thing.UNDERWAY, 1)
        updateCounts(type, ALL, 1)
    }

    open fun handleUpdate(
            typeBefore: Int, stateBefore: Int,
            typeAfter: Int, stateAfter: Int, count: Int) {
        if (stateBefore != Thing.DELETED_FOREVER) {
            updateCounts(typeBefore, stateBefore, -count)
        }
        if (stateAfter != Thing.DELETED_FOREVER) {
            updateCounts(typeAfter, stateAfter, count)
            updateCounts(typeBefore, ALL, -count)
            updateCounts(typeAfter, ALL, count)
        }
    }

    private fun updateCounts(type: Int, state: Int, vary: Int) {
        var count = getCount(type, state)
        count += vary
        setCounts(type, state, count)
    }

    private fun setCounts(type: Int, state: Int, count: Int) {
        mCounts!!.edit().putInt(type.toString() + "_" + state, count).commit()
    }

    private fun init() {
        val editor = mCounts!!.edit()
        var i = Thing.NOTE
        while (i <= Thing.NOTIFY_EMPTY_DELETED) {
            var j = Thing.UNDERWAY
            while (j <= ALL) {
                editor.putInt(i.toString() + "_" + j, 0)
                j++
            }
            i++
        }

        var k = Thing.WELCOME_UNDERWAY
        while (k <= Thing.WELCOME_GOAL) {
            editor.putInt(k.toString() + "_" + Thing.UNDERWAY, 1)
            editor.putInt(k.toString() + "_" + ALL, 1)
            k++
        }

        editor.putInt(Thing.NOTIFY_EMPTY_FINISHED.toString() + "_" + Thing.UNDERWAY, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_FINISHED.toString() + "_" + ALL, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_DELETED.toString() + "_" + Thing.UNDERWAY, 1)
        editor.putInt(Thing.NOTIFY_EMPTY_DELETED.toString() + "_" + ALL, 1)

        editor.commit()
    }

    companion object {
        const val TAG: String = "ThingsCounts"

        const val ALL: Int = Thing.DELETED + 1

        @JvmField
        var sThingsCounts: ThingsCounts? = null

        @JvmStatic
        fun getInstance(context: Context?): ThingsCounts? {
            if (sThingsCounts == null) {
                synchronized(ThingsCounts::class.java) {
                    if (sThingsCounts == null) {
                        sThingsCounts = ThingsCounts(context!!.applicationContext)
                    }
                }
            }
            return sThingsCounts
        }
    }
}
