apply plugin: 'com.android.library'

android {
    namespace 'com.mattprecious.swirl'
    compileSdk 36

    defaultConfig {
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    resourcePrefix 'swirl_'
}
